name: pymc-mlflow-example
channels:
- conda-forge
dependencies:
- arviz[version='>=0.13.0']
- blas
- ipython !=8.7.0
- jax
- jaxlib
- jupyterlab
- lifetimes==0.11.3
- matplotlib[version='>=3.5.1']
- ml_dtypes
- mlflow
- mypy
- myst-nb
- myst-parser
- numpy[version='>=1.17']
- numpyro
- nutpie
- pandas
- pandas-stubs
- pip
- pre-commit[version='>=2.19.0']
- preliz
- pydantic
- pydata-sphinx-theme[version='>=0.12.0.dev0']
- pymc[version='>=5.12.0,<5.16.0']
- pytest==7.0.1
- pytest-cov==3.0.0
- pytest-mock
- ruff[version='>=0.1.4']
- scikit-learn[version='>=1.1.1']
- scipy[version='>=1.11']
- seaborn[version='>=0.12.2']
- sphinx
- sphinx-autodoc-typehints
- sphinx-copybutton
- sphinx-design
- sphinx-notfound-page
- sphinxext-opengraph
- streamlit[version='>=1.25.0']
- typing
- watermark
- xarray
- xarray-einstats[version='>=0.5.1']
- pip:
  # Install from GitHub repo
  - git+https://github.com/pymc-labs/pymc-marketing@main
